services:
  - type: web
    name: django-mini-blog
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --log-level debug wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-mini-blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: django-mini-blog.onrender.com,*.onrender.com
      - key: PYTHON_PATH
        value: /opt/render/project/src:/opt/render/project/src/django-mini-blog-main

databases:
  - name: django-mini-blog-db
    databaseName: django_mini_blog
    user: django_mini_blog_user
    plan: free 